### ISSUE TITLE
New INSPIRE API

### ISSUE THREAD

**Issue by michamos** [dgerosa/filltex#14]
We have released the [new INSPIRE API](https://blog.inspirehep.net/2020/06/we-released-the-new-inspire-api/), and the old API will be taken offline soon (by the end of the summer probably). The docs are available at [inspirehep/rest-api-doc](https://github.com/inspirehep/rest-api-doc).

Let me know if there are any issues with porting your tool.

**Comment by dgerosa** [comment]
Fixed by @dradice. Thanks!
See https://github.com/dgerosa/filltex/pull/18
