### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by lnielsen** [dgerosa/filltex#4]
The repo includes a test file which is great, but it serves more the purpose of an example of how it works. The package ought to include some minimal unit tests that validates the actual output with expected output.

https://docs.pytest.org/en/latest/ can likely help you here.

Related to openjournals/joss-reviews#222

A bonus would be to hook it up with Travis-CI which shouldn't take long.

**Comment by dgerosa** [comment]
Thanks for this comment.

- I have included two simple tests, called `test_ads` and `test_inspire`, to check the web scraping functions against known outputs. These are also described in the readme.
- The previous test.tex file was renamed example.tex
